// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddVideoComponent: typeof import('./src/components/AddVideoComponent.vue')['default']
    CardItemVideoComponent: typeof import('./src/components/CardItemVideoComponent.vue')['default']
    DeleteModalContentComponent: typeof import('./src/components/modal/DeleteModalContentComponent.vue')['default']
    DetailModalContentComponent: typeof import('./src/components/modal/DetailModalContentComponent.vue')['default']
    ListVideosComponent: typeof import('./src/components/ListVideosComponent.vue')['default']
    WrapperModalComponent: typeof import('./src/components/modal/WrapperModalComponent.vue')['default']
  }
}
